apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: c1i4ug7dj-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/c1i4ug7dj-java-springboot-gitops